1/154	http://bw.aok.de/	4
		datenschutz@bw.aok.de
		hv.datenschutz-team@bw.aok.de
		info@bw.aok.de
		service@bw.aok.de
2/154	http://bayern.aok.de/	2
		datenschutz@by.aok.de
		info@service.by.aok.de
3/154	http://bremen.aok.de/	4
		alexey.dietz@hb.aok.de
		datenschutz@hb.aok.de
		info@hb.aok.de
		office@datenschutz.bremen.de
4/154	http://hessen.aok.de/	6
		datenschutz@he.aok.de
		firmenservice@he.aok.de
		lobundkritik@he.aok.de
		poststelle@datenschutz.hessen.de
		service@he.aok.de
		studentenservice@he.aok.de
5/154	http://niedersachsen.aok.de/	3
		abc@abc.de
		aok.service@nds.aok.de
		datenschutz@nds.aok.de
6/154	http://nordost.aok.de/	3
		abc@abc.de
		datenschutz-service@nordost.aok.de
		service@nordost.aok.de
7/154	http://nordwest.aok.de/	2
		datenschutz@nw.aok.de
		kontakt@nw.aok.de
8/154	http://plus.aok.de/	4
		abc@abc.de
		compliance@plus.aok.de
		datenschutz@plus.aok.de
		service@plus.aok.de
9/154	http://rh.aok.de/	5
		abc@abc.de
		aok@rh.aok.de
		datenschutz@rh.aok.de
		datenschutzclarimedis@rh.aok.de
		poststelle@ldi.nrw.de
10/154	http://rps.aok.de/	5
		abc@abc.de
		ansprechstelle@rps.aok.de
		datenschutz@rps.aok.de
		poststelle@datenschutz.rlp.de
		service@rps.aok.de
11/154	http://san.aok.de/	3
		abc@abc.de
		datenschutz@san.aok.de
		service@san.aok.de
12/154	http://www.barmer.de/	3
		datenschutz@barmer.de
		service@barmer.de
		service@barmer.epost.de
13/154	http://www.dak.de/	3
		dsgvo@dak.de
		service@dak.de-mail.de
14/154	http://www.hkk.de/	48
		anderpanke@ressourcenmangel.de
		andrea.reinhold@hkk.de
		angelika.beyer@hkk.de
		anke.gildehaus@hkk.de
		anna.gerdes@hkk.de
		anna.rynkiewicz@hkk.de
		antje.nusche@hkk.de
		axel.kleinert@hkk.de
		behandlungsfehler@hkk.de
		bonusaktiv@hkk.de
		datenschutzbeauftragter@hkk.de
		denis.grochau@hkk.de
		dirk.holzenkaempfer@hkk.de
		gesundheitskarte@hkk.de
		gesundheitskurse@hkk.de
		heidi.schuetze@hkk.de
		heike.grassmann@hkk.de
		ilka.schwania@hkk.de
		info@comspace.de
		info@fitbase.de
		info@hkk.de
		insa.lindenstrauss@hkk.de
		jacqueline.warnken@hkk.de
		jens.dobkowitz@hkk.de
		jens.mertins@hkk.de
		jessica.rohde@hkk.de
		julia.feddersen@hkk.de
		karin.scherbarth@hkk.de
		krankengeld@hkk.de
		marion.deeg@hkk.de
		martina.frenkler@hkk.de
		martina.immoor@hkk.de
		melanie.zukunft@hkk.de
		michael.hansen@hkk.de
		monika.dreher@hkk.de
		mpfer@hkk.de
		sabine.olsson@hkk.de
		sarah.krieger@hkk.de
		stammdatenaenderung@hkk.de
		stefan.klatte@hkk.de
		stephanie.brabender@hkk.de
		support@justme-coach.de
		sven.wellbrock@hkk.de
		tze@hkk.de
		verena.kring@hkk.de
		wilko.steffens@hkk.de
		yvonne.barz@hkk.de
		zuzahlungsbefreiung@hkk.de
15/154	http://www.hek.de/	8
		abrechnungsmanipulation@hek.de
		claudia.siem@hek.de
		datenschutp@hek.de
		datenschutz@hek.de
		joern.bredemeoer@hek.de
		joern.bredemeyer@hek.de
		kontakt@hek.de
		test@example.com
16/154	http://www.kkh.de/	12
		alexander.harrison@kkh.de
		andreas.mergehenn@kkh.de
		datenschutz@kkh.de
		datenschutzservice@kkh.de
		jose.parigi@kkh.de
		kundenwerben@kkh.de
		loretta.rugies@kkh.de
		service@kkh.de
		service@kkh.epost.de
		stephanie.garris@kkh.de
		sumit.tchanana@kkh.de
		vention@kkh.de
17/154	http://www.tk.de/	2
		pressestelle@tk.de
		service@tk.de
18/154	http://www.big-direkt.de/	9
		bettina.kiwitt@big-direkt.de
		birk.bruckhoff@big-direkt.de
		datenschutz@big-direkt.de
		info@big-direkt.de
		info@brainbits.net
		marion.winkler@big-direkt.de
		poststelle@bfdi.bund.de
		presse@big-direkt.de
		vertrieb@big-direkt.de
19/154	http://www.ikk-classic.de/	0
	NO HITS! TODO!
20/154	http://www.ikk-gesundplus.de/	18
		anja.steinmueller@ikk-gesundplus.de
		anja.wolff@ikk-gesundplus.de
		anke.sommermeier@ikk-gesundplus.de
		heike.bohn@ikk-gesundplus.de
		info@ikk-gesundplus.de
		julia.walter@ikk-gesundplus.de
		karsten.zimmermann@ikk-gesundplus.de
		kcdirekt@ikk-gesundplus.de
		kerstin.weigmann@ikk-gesundplus.de
		kpsy-studienzentrum@uk-halle.de
		martin.krenzer@ikk-gesundplus.de
		nancy.kaefer@ikk-gesundplus.de
		nicole.wildfang-reske@ikk-gesundplus.de
		pressestelle@ikk-gesundplus.de
		redaktion@ikk-gesundplus.de
		tanja.becker-glauch@ikk-gesundplus.de
		tanja.ritter@ikk-gesundplus.de
		torsten.may@ikk-gesundplus.de
21/154	http://www.ikk-suedwest.de/	55
		ag@gkv-daten.de
		alexander.effnert@ikk-sw.de
		anne.kroeffges@ikk-sw.de
		antonio.presti@ikk-sw.de
		arno.zimmer@ikk-sw.de
		b.vonderlinde@ikk-sw.de
		behandlungsfehler@ikk-sw.de
		burhan.guelec@ikk-sw.de
		c.wohlfarth@ikk-sw.de
		dany.mueller@ikk-sw.de
		datenschutz@ikk-sw.de
		dav01@b2b.mailorbit.de
		dav@bitmarck.de
		deniz.keles@ikk-sw.de
		elfi-guel-hollweck@kiss-mainz.de
		eva.mueller@ikk-sw.de
		frank.brug@ikk-sw.de
		frank.kraemer@ikk-sw.de
		frank.willim@ikk-sw.de
		gisela.stichler@rps.aok.de
		hotline@itsg.de
		info@haltungbewegung.de
		info@ikk-suedwest.de
		info@kiss-pfalz.de
		info@wekiss.de
		iris.neuhardt@kbs.de
		jana.vonbockelmann@ikk-sw.de
		joerg.kiefer@ikk-sw.de
		joerg.liesenfeld@ikk-sw.de
		katharina.koll@ikk-sw.de
		kathrin.schmid@ikk-sw.de
		kirsten.beck@ikk-sw.de
		kontakt@sekis-trier.de
		kontakt@selbsthilfe-saar.de
		lars.neu@ikk-sw.de
		m.duerrstein@ikk-sw.de
		m.scheliga@ikk-sw.de
		martina.duerr@ikk-sw.de
		michael.thielen@ikk-sw.de
		munira.jasarevic@ikk-sw.de
		nicole.krumnauer@ikk-sw.de
		olaf.schloesser@ikk-sw.de
		oliver.scheid@ikk-sw.de
		poststelle@datenschutz-saarland.de
		poststelle@soziales.saarland.de
		ronald.robinson@ikk-sw.de
		sabrina.hunecker@ikk-sw.de
		sabrina.wagner@ikk-sw.de
		sener.hekim@ikk-sw.de
		service@ikk-sw.de
		stefan.maier@ikk-sw.de
		torsten.scheben@ikk-sw.de
		ute.schoen@ikk-sw.de
		vertriebspartnerservice@ikk-sw.de
		wolfgang.henn@ikk-sw.de
22/154	http://www.ikkbb.de/	27
		cottbus@ikkbb.de
		datenschutz@ikkbb.de
		frankfurt.oder@ikkbb.de
		kc.brandenburg@ikkbb.de
		neuruppin@ikkbb.de
		poststelle@lda.brandenburg.de
		poststelle@masgf.brandenburg.de
		potsdam@ikkbb.de
		service.bernau@ikkbb.de
		service.cottbus@ikkbb.de
		service.eberswalde@ikkbb.de
		service.eisenhuettenstadt@ikkbb.de
		service.finsterwalde@ikkbb.de
		service.fuerstenwalde@ikkbb.de
		service.jueterbog@ikkbb.de
		service.kwh@ikkbb.de
		service.luebben@ikkbb.de
		service.nauen@ikkbb.de
		service.oranienburg@ikkbb.de
		service.perleberg@ikkbb.de
		service.prenzlau@ikkbb.de
		service.rathenow@ikkbb.de
		service.seelow@ikkbb.de
		service.strausberg@ikkbb.de
		service@ikkbb.de-mail.de
		vorstand@ikkbb.de
23/154	http://www.ikk-nord.de/	8
		ag-service-bdf@ikk-nord.de
		ag-service-nb@ikk-nord.de
		ag@gkv-daten.de
		antje.bastian@ikk-nord.de
		dsb@ikk-nord.de
		egk@ikk-nord.de
		mail@ikk-nord.de
		thorsten.harms@ikk-nord.de
24/154	http://www.actimonda.de/	1
		info@actimonda.de
25/154	http://www.atlasbkkahlmann.de/	1
		info@abkka.de
26/154	http://www.audibkk.de/	10
		ansprechstellebthg@audibkk.de
		datenschutz@audibkk.de
		entlassmanagement@audibkk.de
		gesundheitstelefon@audibkk.de
		info@audibkk.de
		korruptionsbeauftragte@audibkk.de
		poststelle@bfdi.bund.de
		poststelle@bfdi.de-mail.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
27/154	http://www.bahn-bkk.de/	3
		contact@incca.com
		service@bahn-bkk.de
		teilhabe-reha@bahn-bkk.de
28/154	http://www.bertelsmann-bkk.de/	46
		aileen.friese@bertelsmann-bkk.de
		alicia.martinez@bertelsmann-bkk.de
		andreas.titlbach@bertelsmann-bkk.de
		anke.klack@bertelsmann-bkk.de
		beate.dembkowski@bertelsmann-bkk.de
		birgit.epp@bertelsmann-bkk.de
		christian.radtke@bertelsmann-bkk.de
		christiane.pauli@bertelsmann-bkk.de
		christina.wagner@bertelsmann-bkk.de
		claudia.paul@bertelsmann-bkk.de
		dagmar.radkowsky@bertelsmann-bkk.de
		datenschutz@bertelsmann-bkk.de
		deutschland@readspeaker.com
		frank.sonntag@bertelsmann-bkk.de
		ggp@bertelsmann-bkk.de
		gisela.wolf@bertelsmann-bkk.de
		info@bertelsmann-bkk.de
		judith.finke@bertelsmann-bkk.de
		karin.schemhaus@bertelsmann-bkk.de
		katja.doerr@bertelsmann-bkk.de
		klaudia.kroll@bertelsmann-bkk.de
		kristin.weiss@bertelsmann-bkk.de
		lisa-marie.klose@bertelsmann-bkk.de
		marc.reichenbach@bertelsmann-bkk.de
		marion.froehning@bertelsmann-bkk.de
		martina.jeschke@bertelsmann-bkk.de
		melanie.blum@bertelsmann-bkk.de
		melanie.mertensjohann@bertelsmann-bkk.de
		miriam.wigand@bertelsmann-bkk.de
		nicole.ackemann@bertelsmann-bkk.de
		nicole.meise@bertelsmann-bkk.de
		olga.rechling@bertelsmann-bkk.de
		peter.cordes@bertelsmann-bkk.de
		petra.uhr@bertelsmann-bkk.de
		pflege@bertelsmann-bkk.de
		poststelle@bfdi.bund.de
		rtl@bertelsmann-bkk.de
		service@bertelsmann-bkk.de
		stefan.doeding@bertelsmann-bkk.de
		sven.sauerwein@bertelsmann-bkk.de
		sverige@readspeaker.com
		thomas.johannwille@bertelsmann-bkk.de
		thomas.loose@bertelsmann-bkk.de
		thorsten.hagmann@bertelsmann-bkk.de
		ute.oehle@bertelsmann-bkk.de
		ute.zurwonne@bertelsmann-bkk.de
29/154	http://www.bkk-bbraun.de/	43
		alice.heinemann@bkk-bbraun.de
		andrea.adler@bkk-bbraun.de
		andrea.juette@bkk-bbraun.de
		angela.moeller@bkk-bbraun.de
		birgit.koerber@bkk-bbraun.de
		bkk-kundenservice@barmenia.de
		carina.wacker@bkk-bbraun.de
		carsten.schroeder@bkk-bbraun.de
		christiane.krug@bkk-bbraun.de
		daniela.guenther@bkk-bbraun.de
		franziska.thraen@bkk-bbraun.de
		helena.zimmer@bkk-bbraun.de
		info@bkk-bbraun.de
		jacqueline.lehmann@bkk-bbraun.de
		juergen.ahrend@bkk-bbraun.de
		jutta.asbrand@bkk-bbraun.de
		kathrin.kuge@bkk-bbraun.de
		klaus.voss@bkk-bbraun.de
		lena-sophie.bohl@bkk-bbraun.de
		lisa.jaeckel@bkk-bbraun.de
		lisa.klippert@bkk-bbraun.de
		manuela.grebe@bkk-bbraun.de
		manuela.wacker@bkk-bbraun.de
		mario.heussner@bkk-bbraun.de
		med.servicetelefon@bkk-bbraun.de
		melanie.aschenbrenner@bkk-bbraun.de
		melissa.siegel@bkk-bbraun.de
		petra.hofmann@bkk-bbraun.de
		ria.kuehl@bkk-bbraun.de
		robert.adam@bkk-bbraun.de
		roxana.andrei@bkk-bbraun.de
		sabrina.hildebrand@bkk-bbraun.de
		sabrina.leese@bkk-bbraun.de
		sandra.kessler@bkk-bbraun.de
		sascha.habedank@bkk-bbraun.de
		sascha.milic@bkk-bbraun.de
		simon.becker@bkk-bbraun.de
		stefanie.norbisrath@bkk-bbraun.de
		stephanie.priester@bkk-bbraun.de
		tanja.merk@bkk-bbraun.de
		thomas.berninger@bkk-bbraun.de
		tina.weidemann@bkk-bbraun.de
		valja.braun@bkk-bbraun.de
30/154	http://www.bkk-bpw.de/	5
		datenschutz@bkk-bpw.de
		info@bkk-bpw.de
		maike.bertelsmeier@bkk-bpw.de
		maike.boxberg@bkk-bpw.de
		stefanie.strombach@bkk-bpw.de
31/154	http://www.bmwbkk.de/	8
		betriebs.krankenkasse@bmw.de
		datenschutzbeauftragter@bmwbkk.de
		leistung@bmwbkk.de%20
		leitung@bmwbkk.de
		mitglied@bmwbkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
32/154	http://www.bkk-pfaff.de/	5
		amuehlberger@bkk-pfaff.de
		ehach@bkk-pfaff.de
		info@bkk-pfaff.de
		mroedler@bkk-pfaff.de
		presse@bkk-pfaff.de
33/154	http://www.bkk-mtu.de/	8
		arbeitgeber-service@bkk-mtu.de
		datenschutz@bkk-mtu.de
		info@bkk-mtu.de
		philipp.maier@bkk-mtu.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		ralph.baumann@bkk-mtu.de
34/154	http://www.siemagbkk.de/	9
		datenschutz@siemagbkk.de
		info@siemag-bkk.de
		info@siemagbkk.de
		jochen.kuehn@siemagbkk.de
		meldung@fehlverhalten.de
		poststelle@bfdi.bund.de
		poststelle@bfdi.de-mail.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
35/154	http://www.evm.de/evm/bkk-evm/	0
	NO HITS! TODO!
36/154	http://www.bkk-ewe.de/	6
		24stunden@bkk-ewe.de
		andreas.zoll@bkk-ewe.de
		imke.schmidt@bkk-ewe.de
		info@bkk-ewe.de
		info@itsc.de
		info@moccaplan.de
37/154	http://www.bkk-gb.de/	5
		info@bkk-gb.de
		markus.biehler@bkk-gb.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de
		redaktion@bkk-gb.de
38/154	http://www.krones-bkk.de/	7
		0info@danubius.de
		bkk.info@krones.com
		hans-georg.eberhard@aurasec.de
		info@danubius.de
		poststelle@datenschutz-bayern.de
		poststelle@stmgp.bayern.de
		xaver.obermeier@krones.com
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bfd0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bkk-mahle.de', port=443): Max retries exceeded with url: /service/meine-patientenverfuegung/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bfd0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.bkk-mahle.de', port=443): Max retries exceeded with url: /service/meine-patientenverfuegung/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bfd0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)'))

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bda0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bkk-mahle.de', port=443): Max retries exceeded with url: /service/korruptionsbekaempfung/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bda0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.bkk-mahle.de', port=443): Max retries exceeded with url: /service/korruptionsbekaempfung/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda51d8bda0>, 'Connection to www.bkk-mahle.de timed out. (connect timeout=10)'))

39/154	http://www.bkk-mahle.de/	13
		datenschutp@bkk\-mahle.de
		datenschutz@bkk-mahle.de
		dkalosoan@bkk\-mahle.de
		dkalosyan@bkk-mahle.de
		info@bkk-mahle.de
		info@bkk\-aesculap.de
		info@bkk\-mahle.de
		nmueller-coonan@bkk-mahle.de
		nmueller\-coonan@bkk\-mahle.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de
		smilbradt@bkk-mahle.de
		smilbradt@bkk\-mahle.de
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7fda51775048>, 'Connection to www.bkk-mem.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.bkk-mem.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fda51775048>, 'Connection to www.bkk-mem.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='www.bkk-mem.de', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fda51775048>, 'Connection to www.bkk-mem.de timed out. (connect timeout=10)'))

40/154	http://www.bkk-mem.de/	0
	NO HITS! TODO!
41/154	http://www.bkk-miele.de/	7
		info@bkk-miele.de
		mail@digitalkombinat.net
		peter.kinnett@bkk-miele.de
		poststelle@bfdi.bund.de
		poststelle@bfdi.de-mail.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError(0, 'Error'))

42/154	http://www.bkk-mobil-oil.de/	3
		bonus@bkk-mobil-oil.de
		datenschutz@bkk-mobil-oil.de
		info@service.bkk-mobil-oil.de
43/154	http://www.bkk-pwc.de/	47
		annalena.schultze@bkk-pwc.de
		anton.klassen@bkk-pwc.de
		celine.warta@bkk-pwc.de
		christiane.fremmer@bkk-pwc.de
		daniel.wolf@bkk-pwc.de
		eileen.dietz@bkk-pwc.de
		fabian.flade@bkk-pwc.de
		frauke.thoben@bkk-pwc.de
		heike.geiger@bkk-pwc.de
		heike.horchler@bkk-pwc.de
		info@bkk-pwc.de
		inge.breitbart@bkk-pwc.de
		isa.schuetz@bkk-pwc.de
		julia.ohl@bkk-pwc.de
		julia.ullrich@bkk-pwc.de
		katrin.vogt@bkk-pwc.de
		kristina.ries@bkk-pwc.de
		lara.heinemann@bkk-pwc.de
		larissa.bachmann@bkk-pwc.de
		lars.grein@bkk-pwc.de
		lena.propf@bkk-pwc.de
		luisa.groth@bkk-pwc.de
		marion.stoehr@bkk-pwc.de
		markus.koch@bkk-pwc.de
		martin.kaiser@bkk-pwc.de
		maximilian.rohde@bkk-pwc.de
		michaela.henkel@bkk-pwc.de
		miriam.guenther@bkk-pwc.de
		nelli.friedrich@bkk-pwc.de
		oliver.hankel@bkk-pwc.de
		patricia.fischer@bkk-pwc.de
		poststelle@bfdi.bund.de
		poststelle@bfdi.de-mail.de
		poststelle@bva.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		ralf.etscheidt@bkk-pwc.de
		roberto.huke@bkk-pwc.de
		sebastian.linke@bkk-pwc.de
		sebastian.rode@bkk-pwc.de
		sonja.scheffer@bkk-pwc.de
		stefanie.sandrock@bkk-pwc.de
		steffen.ruediger@bkk-pwc.de
		swen.duering@bkk-pwc.de
		teresa.behler@bkk-pwc.de
		theresa.dreer@bkk-pwc.de
		tobias.braun@bkk-pwc.de
44/154	http://www.bkkrwe.de/	5
		datenschutz@bkkrwe.de
		info@bkkrwe.de
		info@fkm-verlag.com
		m.schley@bkkrwe.de
		personal-service@bkkrwe.de
45/154	http://www.bkk-sbh.de/	26
		arbeitgeber@bkk-sbh.de
		bkaechele@bkk-sbh.de
		ckammerer@bkk-sbh.de
		datenschutz@bkk-sbh.de
		ebechtold@bkk-sbh.de
		ehuebner@bkk-sbh.de
		gschultis@bkk-sbh.de
		hkohler@bkk-sbh.de
		hrapp@bkk-sbh.de
		info@bkk-sbh.de
		jschanz@bkk-sbh.de
		jschulz@bkk-sbh.de
		kkieser@bkk-sbh.de
		mhaas@bkk-sbh.de
		mmantay@bkk-sbh.de
		mmittner@bkk-sbh.de
		onlineservice@bkk-sbh.de
		poststelle@sm.bwl.de
		rsieger@bkk-sbh.de
		settwein@bkk-sbh.de
		sperson@bkk-sbh.de
		ssaliger@bkk-sbh.de
		sschilling@bkk-sbh.de
		sschmid@bkk-sbh.de
		tnobs@bkk-sbh.de
		twenk@bkk-sbh.de
46/154	http://www.bkk-vdn.de/	8
		christiane.wille@bkk-vdn.de
		datenschutz@bkk-vdn.de
		info@alpha-team.de
		info@bkk-vdn.de
		info@pauly-consult.com
		meinung@bkk-vdn.de
		reha@bkk-vdn.de
		thorsten.kagelmacher@bkk-vdn.de
47/154	http://www.wmf-bkk.de/	6
		datenschutz@wmf-bkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		pschneider@wmf-bkk.de
		service@wmf-bkk.de
48/154	http://www.bkk24.de/	3
		datenschutz@bkk24.de
		info@bkk24.de-mail.de
		info@bkk24.epost.de
49/154	http://www.bkk-achenbach.de/	14
		%20poststelle@ldi.nrw.de
		20poststelle@ldi.nrw.de
		anja.becker@bkk-achenbach.de
		datenschutz@bkk-achenbach.de
		eva-maria.mueller@bkk-achenbach.de
		kontakt@agentur-gladio.de
		matthias.schaelicke@bkk-achenbach.de
		mirko.luecke@bkk-achenbach.de
		peter.docter@bkk-achenbach.de
		poststelle@ldi.nrw.de
		poststelle@mags.nrw.de
		service@bkk-achenbach.de
		tobias.weller@bkk-achenbach.de
		ulrike.hassler@bkk-achenbach.de
50/154	http://www.bkk-advita.de/	3
		datenschutz@bkk24.de
		info@bkk24.de-mail.de
		info@bkk24.epost.de
51/154	http://www.bkk-aesculap.de/	19
		amiekeley@bkk-aesculap.de
		carmbruster@bkk-aesculap.de
		hdirschauer@bkk-aesculap.de
		hschmid@bkk-aesculap.de
		info@bkk-aesculap.de
		jhils@bkk-aesculap.de
		jrebholz@bkk-aesculap.de
		jschroeter@bkk-aesculap.de
		jschweitzer@bkk-aesculap.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de
		rgruber@bkk-aesculap.de
		rgwinner@bkk-aesculap.de
		sjaeger@bkk-aesculap.de
		sking@bkk-aesculap.de
		slabriola@bkk-aesculap.de
		swenzler@bkk-aesculap.de
		tbraunger@bkk-aesculap.de
		vhirt@bkk-aesculap.de
52/154	http://www.bkk-akzo.de/	37
		abrechnungsbetrug@bkk-akzo.de
		abrechnungsbetrug@bkk\-akpo.de
		ausbildung@bkk-akzo.de
		ausbildung@bkk\-akpo.de
		beitraege@bkk-akzo.de
		beitraege@bkk\-akpo.de
		datenschutp(at)bkk\-akpo.de
		datenschutp@bkk\-akpo.de
		datenschutz@bkk-akzo.de
		entgeltersatpleistungen@bkk\-akpo.de
		entgeltersatzleistungen@bkk-akzo.de
		forderungen@bkk-akzo.de
		forderungen@bkk\-akpo.de
		gesundheitskonto@bkk-akzo.de
		gesundheitskonto@bkk\-akpo.de
		info@bkk-akzo.de
		info@bkk\-akpo.de
		info@pone35.de
		info@zone35.de
		kundenberatung@bkk-akzo.de
		kundenberatung@bkk\-akpo.de
		leistungen@bkk-akzo.de
		leistungen@bkk\-akpo.de
		meldungen@bkk-akzo.de
		meldungen@bkk\-akpo.de
		pflegekasse@bkk-akzo.de
		pflegekasse@bkk\-akpo.de
		praevention@bkk-akzo.de
		praevention@bkk\-akpo.de
		rehabilitation@bkk-akzo.de
		rehabilitation@bkk\-akpo.de
		sc.aschaffenburg@bkk-akzo.de
		sc.aschaffenburg@bkk\-akpo.de
		versicherungen@bkk-akzo.de
		versicherungen@bkk\-akpo.de
		vertrieb@bkk-akzo.de
		vertrieb@bkk\-akpo.de
53/154	http://www.bkkdb.de/	8
		bkk.info@db.com
		bkk.marketing@db.com
		carlo.radke@db.com
		florian.wendorf@db.com
		holger.jansen@db.com
		malte.gottlieb@db.com
		udo.mainz@db.com
		ute.manthey-wasserfuhr@db.com
54/154	http://www.bkk-stadt-augsburg.de/	1
		bernd.heidler@bkk-stadt-augsburg.de
55/154	http://www.bkk-diakonie.de/	3
		"mailto:info@bkk-diakonie.de
		fit@job.jpg
		info@bkk-diakonie.de
56/154	http://www.bkk-da.de/	3
		datenschutz@bkk-da.de
		info@bkk-da.de
		poststelle@ldi.nrw.de
57/154	http://www.bkk-euregio.de/	2
		ag@bitmarck-daten.de
		info@bkk-euregio.de
58/154	http://www.bkkexklusiv.de/	0
	NO HITS! TODO!
59/154	http://www.bkk-faber-castell.de/	1
		regen@bkk-faber-castell.de
60/154	http://www.bkk-firmus.de/	7
		datenschutz@bkk-firmus.de
		fehlverhalten@bkk-firmus.de
		ideen@bkk-firmus.de
		info@bkk-firmus.de
		kundenbarometer@bkk-firmus.de
		max.muster@domain.com
		support-de@google.com
61/154	http://www.bkk-freudenberg.de/	49
		ag@bitmarck-daten.de
		agoebig@bkk-freudenberg.de
		anenz@bkk-freudenberg.de
		bkk@bkk-freudenberg.de
		cbrecht@bkk-freudenberg.de
		cfitzer@bkk-freudenberg.de
		chofmann@bkk-freudenberg.de
		ckkleiss@bkk-freudenberg.de
		claubscher@bkk-freudenberg.de
		cmetz@bkk-freudenberg.de
		ctroth@bkk-freudenberg.de
		datenschutz@bkk-freudenberg.de
		deutschland@readspeaker.com
		gsauerwein@bkk-freudenberg.de
		hgudat@bkk-freudenberg.de
		hheller@bkk-freudenberg.de
		hspreckels@bkk-freudenberg.de
		ibruckmaier@bkk-freudenberg.de
		info@bkk-freudenberg.de
		jhordan@bkk-freudenberg.de
		jklauer@bkk-freudenberg.de
		kkleiss@bkk-freudenberg.de
		leckert@bkk-freudenberg.de
		lgropengiesser@bkk-freudenberg.de
		lsattler@bkk-freudenberg.de
		mappel@bkk-freudenberg.de
		mgerner@bkk-freudenberg.de
		mkicinja@bkk-freudenberg.de
		mpohl@bkk-freudenberg.de
		nbackes@bkk-freudenberg.de
		nscheuermann@bkk-freudenberg.de
		nwiegand@bkk-freudenberg.de
		pjuenge@bkk-freudenberg.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		rfischer@bkk-freudenberg.de
		rklocke@bkk-freudenberg.de
		rscheuermann@bkk-freudenberg.de
		rszeilfelder@bkk-freudenberg.de
		sschaefers@bkk-freudenberg.de
		ssczeponek@bkk-freudenberg.de
		sverige@readspeaker.com
		swagner@bkk-freudenberg.de
		szeilfelder@bkk-freudenberg.de
		troth@bkk-freudenberg.de
		tspengler@bkk-freudenberg.de
		ttrautmann@bkk-freudenberg.de
		uweber@bkk-freudenberg.de
62/154	http://www.bkkgs.de/	4
		datenschutz@bkkgs.de
		info@bkkgs.de
		poststelle@bfdi.bund.de
		poststelle@bundesversicherungsamt.de
63/154	http://www.bkk-grillo.de/	1
		info@bkk-grillo.de
64/154	http://www.bkk-henschelplus.de/	39
		a.bensch@bkk-henschelplus.de
		a.kranhold@bkk-henschelplus.de
		a.schirmer@bkk-henschelplus.de
		b.lindemann@bkk-henschelplus.de
		c.foellmer@bkk-henschelplus.de
		d.mueller@bkk-henschelplus.de
		datenschutz@bkk-henschelplus.de
		f.krollpfeiffer@bkk-henschelplus.de
		f.schu@bkk-henschelplus.de
		h.krause@bkk-henschelplus.de
		i.koch@bkk-henschelplus.de
		i.wicke@bkk-henschelplus.de
		info.kassel@neueformen.net
		info@bkk-henschelplus.de
		j.hanke@bkk-henschelplus.de
		j.hofmann@bkk-henschelplus.de
		j.odensass@bkk-henschelplus.de
		j.plettenberg@bkk-henschelplus.de
		j.sammt@bkk-henschelplus.de
		j.schabacker@bkk-henschelplus.de
		k.schmidt@bkk-henschelplus.de
		l.fritz@bkk-henschelplus.de
		m.gunanayagam@bkk-henschelplus.de
		m.klose@bkk-henschelplus.de
		m.riemer@bkk-henschelplus.de
		m.szilagyi@bkk-henschelplus.de
		n.kuehlborn@bkk-henschelplus.de
		p.schulte@bkk-henschelplus.de
		poststelle@rpda.hessen.de
		r.koelsch@bkk-henschelplus.de
		r.mitek@bkk-henschelplus.de
		s.babilon@bkk-henschelplus.de
		s.jensen@bkk-henschelplus.de
		s.schu@bkk-henschelplus.de
		s.tiegel@bkk-henschelplus.de
		t.meschkat@bkk-henschelplus.de
		t.umbach@bkk-henschelplus.de
		v.dinner@bkk-henschelplus.de
		v.leno@bkk-henschelplus.de
65/154	http://www.bkk-hmr.de/	9
		datenschutp@bkk\-hmr.de
		datenschutz@bkk-hmr.de
		info@bkk-hmr.de
		info@bkk\-hmr.de
		info@patientenberatung.de
		poststelle@bfdi.bund.deng
		selbsthilfe-herford@paritaet-nrw.org
		selbsthilfe\-herford@paritaet\-nrw.org
66/154	http://www.bkk-herkules.de/	16
		av@bkk-herkules.de
		b+m@bkk-herkules.de
		datenschutzbeauftragter@bkk-herkules.de
		fibu@bkk-herkules.de
		info@bkk-herkules.de-mail.de
		kundenservice@bkk-herkules.de
		marco.graf@bkk-herkules.de
		marketing@bkk-herkules.de
		sekretariat@bkk-herkules.de
		selbstverwaltung@bkk-herkules.de
		stabsstelle@bkk-herkules.de
		stephan.huhn@bkk-herkules.de
		team1@bkk-herkules.de
		team2@bkk-herkules.de
		team3@bkk-herkules.de
67/154	http://www.karlmayer-bkk.de/	19
		andrea.duening@karlmayer-bkk.de
		andrea.ross@karlmayer-bkk.de
		anett.mahler@karlmayer-bkk.de
		aniel.peter@karlmayer-bkk.de
		dagmar.brettinger@karlmayer-bkk.de
		daniel.peter@karlmayer-bkk.de
		daniele.engel@karlmayer-bkk.de
		gesundheitszentrum@karlmayer-bkk.de
		grit.jungmann@karlmayer-bkk.de
		harald.eyssen@karlmayer-bkk.de
		info@karlmayer-bkk.de
		janine.schwalb@karlmayer-bkk.de
		juergen.schmidt@karlmayer-bkk.de
		katja.berker@karlmayer-bkk.de
		marielle.lienert@karlmayer-bkk.de
		poststelle@rpda.hessen.de
		silke.krahberg@karlmayer-bkk.de
		sven.strauch@karlmayer-bkk.de
		werner.fertig@karlmayer-bkk.de
68/154	http://www.bkk-kba.de/	5
		anke.gast@bkk-kba.de
		datenschutzbeauftragter@bkk-kba.de
		holm.coun@bkk-kba.de
		kristina.maslin@bkk-kba.de
		thomas.luedecke@bkk-kba.de
69/154	http://www.bkk-linde.de/	4
		app@bkk-linde.de
		arbeitgeberservice@bkk-linde.de
		info@bkk-linde.de
		sabine.braun@bkk-linde.de
70/154	http://www.bkk-melitta.de/	7
		aileen.wegwerth@bkk-melitta.de
		bkk-baby@bkk-melitta.de
		datenschutz@bkk-melitta.de
		info@bkk-melitta.de
		poststelle@bfdi.bund.de$20
		poststelle@bundesversicherungsamt.de
71/154	http://www.bkkpfalz.de/	12
		aninfo@bkkpfalz.de
		datenschutz@bkkpfalz.de
		feedback@bkkpfalz.de
		info@bkkpfalz.de
		magazin@bkkpfalz.de
		mail@ueberbit.com
		mstamm@bkkpfalz.de
		postfach@bkkpfalz.de-mail.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		vertrieb@bkkpfalz.de
72/154	http://www.bkk-provita.de/	4
		datenschutz@bkk-provita.de
		info@bkk-provita.de
		widerruf@bkk-provita.de
		wolfgang.huber@bkk-provita.de
73/154	http://www.bkk-public.de/	10
		datenschutz@bkk-public.de
		dietrich.dirk@bkk-public.de
		grosser.regina@bkk-public.de
		hapka.irena@bkk-public.de
		heuer.heike@bkk-public.de
		info@sal-a.de
		it-sicherheit@bkk-public.de
		meyer.manuela@bkk-public.de
		ranft.solveig@bkk-public.de
		service@bkk-public.de
74/154	http://www.bkk-rrw.de/	15
		akunz@bkk-rrw.de
		awaechter@bkk-rrw.de
		datenschutz@bkk-rrw.de
		datenschutzbeauftragte@bkk-rrw.de
		dhandloser@bkk-rrw.de
		info@bkk-rrw.de
		mbraun@bkk-rrw.de
		nguenter@bkk-rrw.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de
		pporada@bkk-rrw.de
		slevendeli@bkk-rrw.de
		sloehning@bkk-rrw.de
		strautner@bkk-rrw.de
		vmattheis@bkk-rrw.de
75/154	http://www.bkk-salzgitter.de/	10
		datenschutz@bkk-salzgitter.de
		dietrich.dirk@bkk-salzgitter.de
		grosser.regina@bkk-salzgitter.de
		hapka.irena@bkk-salzgitter.de
		heuer.heike@bkk-salzgitter.de
		info@sal-a.de
		it-sicherheit@bkk-salzgitter.de
		meyer.manuela@bkk-salzgitter.de
		ranft.solveig@bkk-salzgitter.de
		service@bkk-salzgitter.de
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fda527582b0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.mein-pr%c3%a4ventionsportal.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda527582b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.mein-pr%c3%a4ventionsportal.de', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda527582b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

76/154	http://www.bkk-scheufelen.de/	17
		beitrag@bkk-scheufelen.de
		bmeissner@bkk-scheufelen.de
		ckuhn@bkk-scheufelen.de
		ctrautwein@bkk-scheufelen.de
		datenschutz@bkk-scheufelen.de
		fpallinger@bkk-scheufelen.de
		gesundheitsfoerderung@bkk-dv.de
		info@bkk-scheufelen.de
		kontakt@co-in.de
		kschwarz@bkk-scheufelen.de
		loberlaender@bkk-scheufelen.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de
		sachleistungen2@bkk-scheufelen.de
		sdannenmann@bkk-scheufelen.de
		slukoschek@bkk-scheufelen.de
		wallgaier@bkk-scheufelen.de
77/154	http://www.bkk-technoform.de/	0
	NO HITS! TODO!
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/usr/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib64/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib64/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib64/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1034: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 693, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.bkk-verbundplus.de', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 659, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 659, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 238, in resolve_redirects
    **adapter_kwargs
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.bkk-verbundplus.de', port=443): Read timed out. (read timeout=10)

78/154	http://www.bkk-verbundplus.de/	9
		bernburg@bkkvp.de
		biberach@bkkvp.de
		dmp@bkkvp.de
		dresden@bkkvp.de
		karlsruhe@bkkvp.de
		krankenhaus@bkkvp.de
		pflege@bkkvp.de
		stuttgart@bkkvp.de
		ulm@bkkvp.de
79/154	http://www.meine-krankenkasse.de/	9
		christian.lucht@bkk-vbu.de
		datenschutzbeauftragter@bkk-vbu.de
		ellen.zimmermann@bkk-vbu.de
		entlassmanagement@bkk-vbu.de
		firmenkunden@bkk-vbu.de
		info@bkk-vbu.de
		max.mustermann@muster.xyz
		pflege@bkk-vbu.de
		sylvie.renz@bkk-vbu.de
80/154	http://www.bkk-vital.de/	12
		aninfo@bkkpfalz.de
		datenschutz@bkkpfalz.de
		feedback@bkkpfalz.de
		info@bkkpfalz.de
		magazin@bkkpfalz.de
		mail@ueberbit.com
		mstamm@bkkpfalz.de
		postfach@bkkpfalz.de-mail.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		vertrieb@bkkpfalz.de
81/154	http://www.bkk-voralb.de/	6
		beitraege@bkk-voralb.de
		datenschutz@bkk-voralb.de
		info@bkk-voralb.de
		poststelle@lfdi.bwl.de
		poststelle@sm.bwl.de-mail.de
82/154	http://www.bkk-werra-meissner.de/	5
		anja.hildebrandt@bkk-wm.de
		datenschutz@bkk-wm.de
		info@bkk-wm.de
		poststelle@datenschutz.hessen.de
		poststelle@rpda.hessen.de
83/154	http://www.bkk-wf.de/	7
		datenschutz@bkk-wf.de
		info@bkk-wf.de
		poststelle@bfdi.bund.de
		poststelle@bfdi.de-mail.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		support-de@google.com
84/154	http://www.bkk-wuerth.de/	0
	NO HITS! TODO!
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda5253b128>, 'Connection to www.bkk-zf-partner.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bkk-zf-partner.de', port=443): Max retries exceeded with url: /ansprechpartner/kontaktformulare/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda5253b128>, 'Connection to www.bkk-zf-partner.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.bkk-zf-partner.de', port=443): Max retries exceeded with url: /ansprechpartner/kontaktformulare/ (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda5253b128>, 'Connection to www.bkk-zf-partner.de timed out. (connect timeout=10)'))

85/154	http://www.bkk-zf-partner.de/	0
	NO HITS! TODO!
86/154	http://www.bosch-bkk.de/	25
		andrea.conrad@bosch-bkk.de
		andrea.hofmann@bosch-bkk.de
		andreas.schwarz@bosch-bkk.de
		andreas.velten@bosch-bkk.de
		anna.weiss@bosch-bkk.de
		claudia.hage@bosch-bkk.de
		datenschutz@bosch-bkk.de
		dieter.gottschalt@bosch-bkk.de
		gudrun.dopatka@bosch-bkk.de
		info@bosch-bkk.de
		kathleen.minkenberg@bosch-bkk.de
		lothar.geitner@bosch-bkk.de
		monique.reb@bosch-bkk.de
		nadja.schumacher@bosch-bkk.de
		oezguel.diler@bosch-bkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		ralf.hartmann@bosch-bkk.de
		ramona.neser@bosch-bkk.de
		sigrid.leistner@bosch-bkk.de
		stefan.straub@bosch-bkk.de
		susanne.dlugosch@bosch-bkk.de
		tobias.bareiss@bosch-bkk.de
		uwe.wustmann@bosch-bkk.de
87/154	http://www.brandenburgische-bkk.de/	34
		
 <script type='text/javascript'>
 <!--
 var prefix = 'ma' + 'il' + 'to';
 var path = 'hr' + 'ef' + '=';
 var addy25784 = 'poststelle' + '@';
 addy25784 = addy25784 + 'bvamt' + '.' + 'de-mail' + '.' + 'de';
 document.write('<a ' + path + '\'' + prefix + ':' + addy25784 + '\'>');
 document.write(addy25784);
 document.write('<\/a>');
 //-->\n </script><script type='text/javascript'>
 <!--
 document.write('<span style=\'display: none;\'>');
 //-->
 </script>this email address is being protected from spambots. you need javascript enabled to view it.
 <script type='text/javascript'>
 <!--
 document.write('</');
 document.write('span>');
 //-->
 </script>
		aleksandra.binder-luczak@brandenburgische-bkk.de
		alexandra.zipfel@brandenburgische-bkk.de
		anke.zacharias@brandenburgische-bkk.de
		anne.benkert@brandenburgische-bkk.de
		annekathrin.zacharias@brandenburgische-bkk.de
		annett.pfaffe@brandenburgische-bkk.de
		annette.rogalla@brandenburgische-bkk.de
		birgit.becker@brandenburgische-bkk.de
		caren.wuttig@brandenburgische-bkk.de
		carolin.krzycki@brandenburgische-bkk.de
		claudia.lipinsky@brandenburgische-bkk.de
		claudia.richter@brandenburgische-bkk.de
		ines.geike@brandenburgische-bkk.de
		kathrin.wormann@brandenburgische-bkk.de
		kerstin.jank@brandenburgische-bkk.de
		kerstin.koenig@brandenburgische-bkk.de
		kontakt@brandenburgische-bkk.de
		mandy.bretag@brandenburgische-bkk.de
		marlen.anders@brandenburgische-bkk.de
		maximilian.wrobel@brandenburgische-bkk.de
		michael.grutza@brandenburgische-bkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		service@brandenburgische-bkk.de
		simone.kotsch@brandenburgische-bkk.de
		steffi.haberstock@brandenburgische-bkk.de
		susanne.fernkorn@brandenburgische-bkk.de
		sylke.sander@brandenburgische-bkk.de
		theresa.ander@b-bkk.de
		theresa.ander@brandenburgische-bkk.de
		websupport@dsg1.de
		wenke.klein@brandenburgische-bkk.de
88/154	http://www.continentale-bkk.de/	7
		datenschutz@continentale-bkk.de
		i.schwager-elis@continentale-bkk.de
		kundenservice@continentale-bkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
		support-de@google.com
89/154	http://www.daimler-bkk.com/	7
		angela.lechner@daimler.com
		benjamin.plocher@daimler-bkk.com
		hartmut.steffens@daimler-bkk.com
		marketing@daimler-bkk.com
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		poststelle@bvamt.de-mail.de
90/154	http://www.debeka-bkk.de/	4
		datenschutz@debeka-bkk.de
		info@debeka-bkk.de
		lob+kritik@debeka-bkk.de
		poststelle@bfdi.bund.de
91/154	http://www.die-bergische-kk.de/	4
		alf.dahl@die-bergische-kk.de
		datenschutz@die-bergische-kk.de
		info@die-bergische-kk.de
		manuel.avella-salazar@die-bergische-kk.de
Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 631, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 722, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'javascript://www.energie-bkk.de/impressum()'

92/154	http://www.energie-bkk.de/	9
		datenschutz@energie-bkk.de
		frank.bruns@energie-bkk.de
		info@energie-bkk.de
		martin.engelbert@energie-bkk.de
		michael.baum@energie-bkk.de
		poststelle@bfdi.bund.de
		poststelle@bvamt.bund.de
		ronald.schultz@energie-bkk.de
		steffen.steinbeck@energie-bkk.de
93/154	http://www.ey-bkk.de/	23
		andrea.halt@ey-bkk.de
		andrea.wambach@ey-bkk.de
		beitraege@ey-bkk.de
		bjoern.kirchberg@ey-bkk.de
		christin.kuehlborn@ey-bkk.de
		info@ey-bkk.de
		inka.habermann@ey-bkk.de
		jorina.gross@ey-bkk.de
		juergen.mosebach@ey-bkk.de
		lars.hartung@ey-bkk.de
		lisa.reinbold@ey-bkk.de
		markus.sandrock@ey-bkk.de
		martin.muench@ey-bkk.de
		patric.mertke@ey-bkk.de
		peter.wenzel@ey-bkk.de
		pflege@ey-bkk.de
		poststelle@bva.de
		sabine.schneider@ey-bkk.de
		sarah.orth@ey-bkk.de
		steffen.schneider@ey-bkk.de
		tamara.eskuche@ey-bkk.de
		tanja.heidt-wolf@ey-bkk.de
		vorstand@ey-bkk.de
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.7/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 314, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.7/site-packages/urllib3/connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda528731d0>, 'Connection to www.bkk-textilgruppe-hof.de timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bkk-textilgruppe-hof.de', port=443): Max retries exceeded with url: /wir-ueber-uns.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda528731d0>, 'Connection to www.bkk-textilgruppe-hof.de timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mail-crawler.py", line 136, in process_url
    request = requests.get(target, allow_redirects=True, timeout=10)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='www.bkk-textilgruppe-hof.de', port=443): Max retries exceeded with url: /wir-ueber-uns.html (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fda528731d0>, 'Connection to www.bkk-textilgruppe-hof.de timed out. (connect timeout=10)'))
